### PR TITLE
Skimmed Grammar and Spelling : anna_post_true

### PR DESCRIPTION
**Pull request by Lykayos**
Assuming it's welcome, this is a collection of minor grammar and
spelling errors I noticed while reading the scene. It is, in no way,
comprehensive; any changes that may have altered the meaning or
connotation of a message were left out.

Cheers, L

### CODE REVIEW

**Comment by Lykayos** [comment]
Attempt three! Hopefully to the correct place this time. You all corrected most things I noticed already; here's what's left.

Should be straightforward other than line 140 which reads and looks like an Adverbial Concession. After thinking it over, I'm fairly sure it's a depend clause after an independent clause.

**Comment by AWSWCommunity** [comment]
Thanks for pointing these out! I'm glad there's others auditing the code. 

Before I merge this PR, can you explain the rationale behind flipping the clauses on line 94? I thought it sounded better the other way.

**Comment by Lykayos** [comment]
You don't place a comma after an independent clause that's being followed by a dependent clause unless the latter is also a concessional statement. You could switch the order of the clauses back and simply remove the comma. Instinctively, I took the choice that also moved the following noun and pronoun closer together, but either can be made correct. 

If you'd rather have the linguistic style of the latter, I can reverse the clauses for you and simply remove the stray comma.

**Comment by AWSWCommunity** [comment]
Thanks, I see now. I'd like to stay to true to the writer's original style, so go ahead and reverse it.

**Comment by Lykayos** [comment]
And I just now noticed after years of using github, that I cannot amend a branch with an outstanding PR. Would you rather I make another PR or just pile another commit onto this one?

**Pull request merged**
